#!/usr/bin/env bash
# This script updates /etc/hosts to change localhost and facebook.com IP mappings.

# Backup the original /etc/hosts file
cp /etc/hosts /etc/hosts.bak

# Remove any existing localhost or facebook.com entries
sed -i '/localhost/d' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts

# Add new entries
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
